[package]
name = "rust-algorand"
version = "0.1.0"
edition = "2021"

[dependencies]
ux = "0.1.3"
hex = "0.4.3"
rand = "0.7.3"
sha2 = "0.9.8"
base32 = "0.4.0"
base64 = "0.13.0"
quick-error = "2.0.1"
ed25519-dalek = "1.0.1"
