name: Create Tag

on:
  push:
    branches: [ master ]

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "{ \"version\": $(cat Cargo.toml  | grep -E '^version = ' | awk '{print $3}')}" > package.json
      - uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
